-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgatP6kWtpFrh0T02o
LcSHoPucyCR/sCPsuET6MrYHRTqgCgYIKoZIzj0DAQehRANCAASTi921ePrKqHks
JpRh0OnReRz/v7Si2R7tjB3PxwtYBjrXtNn9lqH/JeRbVy3dQd3HKAdnwaBGdRbG
zFQoZK+K
-----END PRIVATE KEY-----